# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mdb-ios-mp5_message_my_friends' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mdb-ios-mp5_message_my_friends
  pod 'iosManagers'
  
  
  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  
  # Pods for UI
  pod 'JGProgressHUD', :inhibit_warnings => true
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4', :inhibit_warnings => true
  pod 'SkyFloatingLabelTextField', '~> 3.0', :inhibit_warnings => true
  
  pod 'IQKeyboardManager', :inhibit_warnings => true

end
